spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_service_db
    username: postgres
    password: pass345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect